In [26]:
import numpy as np

In [11]:
f= open('input.txt')
content = f.read()
content = content.split("\n\n")

In [45]:
numbers = content[0].split(',')
boards = content[1:]

In [300]:
class Bingo:
    
    def __init__(self):
        self.boards = []
        
    def add_board(self, grid_values):
        self.boards.append(Board(grid_values))
        
    def draw_number(self, nb):
        for board in self.boards:
            has_win = board.play(nb)
            if has_win:
                return has_win,board.grid_values,board.grid_bool
        return False,[],[]
    
    
    def party(self,numbers):
        for number in numbers:
            stop, grid, grid_bools = self.draw_number(number)
            if stop:
                return number,grid, grid_bools
                
class Board:
    
    def __init__(self, grid_values):
        self.grid_values = np.array([line.split() for line in grid_values.split("\n") if len(line)>0 ])
        self.grid_bool = np.zeros((5,5))
        
    def play(self,nb):
        ind = np.argwhere(self.grid_values == nb)
        if len(ind)>0:
            self.grid_bool[tuple(ind[0])]=1
        return self.has_win()
    
    def has_win(self):
        has_win_bool = any([self.grid_bool[i,:].all() for i in range(5)] + [self.grid_bool[:,j].all() for j in range(5)])
        if has_win_bool:
            print(self.grid_values, self.grid_bool)
        return has_win_bool

In [301]:
bingo = Bingo()
for board in boards:
    bingo.add_board(board)
number, grid, bools = bingo.party(numbers)

[['99' '19' '74' '0' '9']
 ['59' '92' '67' '82' '69']
 ['72' '46' '63' '51' '77']
 ['2' '45' '66' '28' '12']
 ['93' '38' '15' '64' '27']] [[0. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 1. 1. 1. 0.]]


In [302]:
grid[bools==0].astype(float).sum()*float(number)

44088.0